language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - DEPS=lowest
    - php: 7.3
      env:
        - BENCHMARKS=true
        - CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
    - php: 8.0
      env:
        - DEPS=lowest
        - COMPOSER_ARGS="$COMPOSER_ARGS --ignore-platform-req=php"
        - PROXY_DEPS="ocramius/proxy-manager:^2.11.0 doctrine/annotations:^1.7.0"
    - php: 8.0
      env:
        - COMPOSER_ARGS="$COMPOSER_ARGS --ignore-platform-req=php"

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - travis_retry composer install $COMPOSER_ARGS
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - if [[ $PROXY_DEPS != '' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $PROXY_DEPS ; fi
  - stty cols 120 && composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $BENCHMARKS == 'true' ]]; then vendor/bin/phpbench run --revs=2 --iterations=2 --report=aggregate ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then vendor/bin/php-coveralls -v ; fi

notifications:
  email: false
